---
- name: Configure master instances
  hosts: oo_masters_to_config
  roles:
  - openshift_master
  - openshift_examples
  - role: fluentd_master
    when: openshift.common.use_fluentd | bool
  tasks:
  - name: Create group for deployment type
    group_by: key=oo_masters_deployment_type_{{ openshift.common.deployment_type }}
    changed_when: False

# Additional instance config for online deployments
- name: Additional instance config
  hosts: oo_masters_deployment_type_online
  roles:
  - pods
  - os_env_extras
  - dockercfg
  - role: openshift_expand_partition
    oep_drive: "/dev/xvda"
    oep_partition: 3
    oep_file_system: "xfs"

